### ISSUE TITLE
[Proposal] Add ARM64 support

### ISSUE THREAD

**Issue by roxk** [madskristensen/MIDL#16]
**Is your feature request related to a problem? Please describe.**
As titled. ARM toolchain is going to be ready soon and we should be proactive in supporting that as well.

**Describe the solution you'd like**
Add ARM64 support.

**Describe alternatives you've considered**
N/A

**Additional context**
Noticed it when playing around with the extension manifest
![image](https://user-images.githubusercontent.com/16918354/197383961-db542ffc-f544-44d0-90eb-e7c65ac95410.png)

**Comment by snickler** [comment]
I'm glad to see this issue since I was just about to go ahead and do this myself.
